### ISSUE TITLE
mate-indicator-applet can not auto scale image

### ISSUE THREAD

**Issue by rocket049** [mate-desktop/mate-indicator-applet#38]
#### Expected behaviour
When show large image, it should auto scale image to fit the indicator area.

#### Actual behaviour
When show large image, it will not auto scale image to fit the indicator area, but show part of the image.
![systray1](https://user-images.githubusercontent.com/40598197/52944033-719b3f00-33a9-11e9-8fb8-7fb7850f1ec6.png)

#### Steps to reproduce the behaviour
install and run nutstore: (https://www.jianguoyun.com/s/downloads) 

#### MATE general version
1.20.1-2ubuntu1

#### Package version
1.20.0-1

#### Linux Distribution
ubuntu-mate 18.04.2

#### Link to downstream report of your Distribution
![systray1](https://user-images.githubusercontent.com/40598197/52944033-719b3f00-33a9-11e9-8fb8-7fb7850f1ec6.png)

**Comment by monsta** [comment]
Fixed in 1.22.1 by https://github.com/mate-desktop/mate-indicator-applet/pull/43.

**Comment by rocket049** [comment]
@monsta This problem has not been completely solved. When the parameter of the `set_icon` function is the full path of the icon file, the icon still cannot be resized.
The same error occurs in these functions:
* set_icon 
* set_icon_full
* set_attention_icon
* set_attention_icon_full
